### ISSUE TITLE
SerialException when running power-status.py

### ISSUE THREAD

**Issue by xinyuwang1209** [calvous/Surface-Fakedev#1]
I use Surface Pro 4 with Archlinux and i3wm. After I run the command:
```
sudo ./power-status.py adp1.uevent
```
I got this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/serial/serialposix.py", line 323, in _reconfigure_port
    orig_attr = termios.tcgetattr(self.fd)
termios.error: (5, 'Input/output error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./power-status.py", line 446, in <module>
    main()
  File "./power-status.py", line 424, in main
    dev = setup_device(args.device, args.baud)
  File "./power-status.py", line 30, in setup_device
    timeout=0,
  File "/usr/lib/python3.7/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/usr/lib/python3.7/site-packages/serial/serialposix.py", line 272, in open
    self._reconfigure_port(force_update=True)
  File "/usr/lib/python3.7/site-packages/serial/serialposix.py", line 326, in _reconfigure_port
    raise SerialException("Could not configure port: {}".format(msg))
serial.serialutil.SerialException: Could not configure port: (5, 'Input/output error')
```

**Comment by calvous** [comment]
The output of adp1.uevent is not really important. Just comment this line with '#' in /sbin/pwr-cron.sh. Does bat1.uevent work? If you have only one battery make sure it is also reflected in this file. (comment with '#' bat2.uevent if so)
The output should be like this:
```
$ sudo ./power-status.py adp1.uevent
POWER_SUPPLY_ONLINE=0
POWER_SUPPLY_NAME=ADP1
```
The battery monitor in i3status does not read this. It uses this
```
$ sudo ./power-status.py bat1.uevent
POWER_SUPPLY_STATUS=Discharging
.
.
.
```

**Comment by xinyuwang1209** [comment]
Thank you for the help. Both 
```
sudo ./power-status.py adp1.uevent
```
and
```
sudo ./power-status.py bat1.uevent
```
returns the same error. 


By the way, I install python-serial by 
```
sudo pip install serial
sudo pip install pyserial
```
Do you think this will be the potential cause of the error I got? Thanks.

**Comment by calvous** [comment]
pyserial is the package needed. You also need crcmod. It has to be for python3. It must show something like this in your file system.
```
$ ls -l /usr/lib/python3.7/site-packages/crcmod
total 84
-rwxr-xr-x 1 root root 18536 Oct  3 02:45 _crcfunext.cpython-37m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root  3702 Oct  3 02:45 _crcfunpy.py
-rw-r--r-- 1 root root 16610 Oct  3 02:45 crcmod.py
-rw-r--r-- 1 root root   194 Oct  3 02:45 __init__.py
-rw-r--r-- 1 root root  9606 Oct  3 02:45 predefined.py
drwxr-xr-x 2 root root  4096 Oct  3 02:45 __pycache__
-rw-r--r-- 1 root root 18433 Oct  3 02:45 test.py
```
and
```
$ ls -l /usr/lib/python3.7/site-packages/serial/
total 196
-rw-r--r-- 1 root root  3172 Jun 30 12:52 __init__.py
drwxr-xr-x 2 root root  4096 Oct  3 02:42 __pycache__
-rw-r--r-- 1 root root 59444 Jun 30 12:52 rfc2217.py
-rw-r--r-- 1 root root  3265 Jun 30 12:52 rs485.py
-rw-r--r-- 1 root root  9104 Jun 30 12:52 serialcli.py
-rw-r--r-- 1 root root  8414 Jun 30 12:52 serialjava.py
-rw-r--r-- 1 root root 31654 Jun 30 12:52 serialposix.py
-rw-r--r-- 1 root root 21692 Jun 30 12:52 serialutil.py
-rw-r--r-- 1 root root 20087 Jun 30 12:52 serialwin32.py
drwxr-xr-x 3 root root  4096 Oct  3 02:42 threaded
drwxr-xr-x 3 root root  4096 Oct  3 02:42 tools
drwxr-xr-x 3 root root  4096 Oct  3 02:42 urlhandler
-rw-r--r-- 1 root root 10853 Jun 30 12:52 win32.py
```

**Comment by calvous** [comment]
https://pypi.org/project/crcmod/
https://github.com/pyserial/pyserial

**Comment by xinyuwang1209** [comment]
Here is my returned result:
```
$ python -V
Python 3.7.0
```

```
$ ls -l /usr/lib/python3.7/site-packages/crcmod
total 108
-rwxr-xr-x 1 root root 44216 Oct 14 23:38 _crcfunext.cpython-37m-x86_64-linux-gnu.so
-rw-r--r-- 1 root root  3702 Oct 14 23:38 _crcfunpy.py
-rw-r--r-- 1 root root 16610 Oct 14 23:38 crcmod.py
-rw-r--r-- 1 root root   194 Oct 14 23:38 __init__.py
-rw-r--r-- 1 root root  9606 Oct 14 23:38 predefined.py
drwxr-xr-x 2 root root  4096 Oct 14 23:38 __pycache__
-rw-r--r-- 1 root root 18433 Oct 14 23:38 test.py
```

```
$ ls -l /usr/lib/python3.7/site-packages/serial/
total 196
-rw-r--r-- 1 root root  3172 Jun 30 12:52 __init__.py
drwxr-xr-x 2 root root  4096 Oct 15 14:04 __pycache__
-rw-r--r-- 1 root root 59444 Jun 30 12:52 rfc2217.py
-rw-r--r-- 1 root root  3265 Jun 30 12:52 rs485.py
-rw-r--r-- 1 root root  9104 Jun 30 12:52 serialcli.py
-rw-r--r-- 1 root root  8414 Jun 30 12:52 serialjava.py
-rw-r--r-- 1 root root 31654 Jun 30 12:52 serialposix.py
-rw-r--r-- 1 root root 21692 Jun 30 12:52 serialutil.py
-rw-r--r-- 1 root root 20087 Jun 30 12:52 serialwin32.py
drwxr-xr-x 3 root root  4096 Oct 15 14:04 threaded
drwxr-xr-x 3 root root  4096 Oct 15 14:04 tools
drwxr-xr-x 3 root root  4096 Oct 15 14:04 urlhandler
-rw-r--r-- 1 root root 10853 Jun 30 12:52 win32.py
```

I tried to uninstall pyserial and installed it again using 
```
sudo pacman -S python-pyserial
```
but same error still appear.

**Comment by calvous** [comment]
@xinyuwang1209 
Please download and try the original from @qzed here https://gist.github.com/qzed/01a93568efb863f1b7887f0f375c03fc
It does not have the .uevent option. Run it as root with bat1.pretty or bat1._sta or bat1._bix
This way we will see wether I screwed up on the py script. If this does not run either I am at the end of it and cannot help you there. I only reformatted the output to fit uevent. I do not really know, what's going on in this script. But let me know anyways. Do not forget to edit the script for the correct ttyS

**Comment by qzed** [comment]
To chime in for a bit: I'm not sure if this works on the Surface Pro 4, I only know that it works on 5th generation Surface devices (Laptop, Book 2, Pro 2017). A DSDT would be helpful to check that.

The error message seems to indicate that the port can not be configured correctly. This can happen when the wrong port is selected. You can check this by having a look at the `dmesg` output, specifically

```
dmesg | grep ttyS
```

This should print the port that should be used.

**Comment by calvous** [comment]
Thanks a lot @qzed . I already got lost here :+1: 
@xinyuwang1209 
Try this command and see if it returns something.
On my box:
```
$ dmesg|grep ttyS
[    3.704490] dw-apb-uart.2: ttyS0 at MMIO 0xa1336000 (irq = 20, base_baud = 3000000) is a 16550A
```
Edit the "power-status.py" script with the values found (line 15 and 16). But tweaking the values on the Surface Pro 1796 never produced the same error than yours does.

**Comment by calvous** [comment]
Thanks a lot @qzed . I already got lost here :+1: 
@xinyuwang1209 
Try this command and see if it returns something.
On my box:
```
$ dmesg|grep ttyS
[    3.704490] dw-apb-uart.2: ttyS0 at MMIO 0xa1336000 (irq = 20, base_baud = 3000000) is a 16550A
```
Edit the "power-status.py" script with the values found (line 15 and 16). But tweaking the values on the Surface Pro 1796 never produced the same error than yours does.

**Comment by calvous** [comment]
Sry, I clicked on close comment and it closes the issue.

**Comment by qzed** [comment]
@calvous No problem, seems like it's failing in my script so it's my responsibility after all :-)

**Comment by xinyuwang1209** [comment]
@calvous @qzed Thanks for the help!

dmesg does not return anything with ttyS:
```
$ uname -r
4.18.7-1-surface
```
```
$ dmesg | grep ttyS
```
The message I got from dmesg with acpi is also different from the one discussed in 
https://github.com/jakeday/linux-surface/issues/28

```
$ dmesg | grep acpi
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x01] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x02] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x03] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x04] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x05] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x06] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x07] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x08] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x09] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x0a] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x0b] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x0c] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x0d] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x0e] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x0f] high edge lint[0x1])
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0x10] high edge lint[0x1])
[    0.080054] acpiphp: ACPI Hot Plug PCI Controller Driver version: 0.5
[    0.180566] acpi PNP0A08:00: _OSC: OS supports [ExtendedConfig Segments MSI]
[    0.180678] acpi PNP0A08:00: PCIe port services disabled; not requesting _OSC control
[    0.517373] clocksource: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[    1.834230] surface_acpi: Microsoft Surface ACPI Driver version 0.1
[    1.834260] surface_acpi: Attaching device
[  280.923282] surface_acpi: Event received 81
[  282.099253] surface_acpi: Event received 81
[  282.099258] surface_acpi: Event received 80
[  282.103198] surface_acpi: Event received 80
[  292.290616] surface_acpi: Event received 81
[  292.290620] surface_acpi: Event received 80
[  292.295676] surface_acpi: Event received 80
[  305.668353] surface_acpi: Event received 81
[  305.668357] surface_acpi: Event received 80
[  305.672239] surface_acpi: Event received 80
[  307.709935] surface_acpi: Event received 81
[  307.709938] surface_acpi: Event received 80
[  307.714917] surface_acpi: Event received 80
[  315.890770] surface_acpi: Event received 81
[  315.890773] surface_acpi: Event received 80
...
```

**Comment by qzed** [comment]
@xinyuwang1209 could you upload an ACPI dump (just run `sudo acpidump > acpidata.dat` and upload the `acpidata.dat` file)?

**Comment by xinyuwang1209** [comment]
Here is the data file:
https://github.com/xinyuwang1209/acpi/blob/master/acpidata.dat

**Comment by qzed** [comment]
@xinyuwang1209 Yeah, sorry that DSDT is vastly different from the 5th generation devices. The script won't work with this, and I don't have a Surface Pro 4 to check out in detail why the battery is not working there.
